/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica9;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author carlo
 */
public class DataView extends javax.swing.JFrame {

    private final DBAccess dbAccess;
    private final JFrame login;
    private DefaultListModel modelTableNames = new DefaultListModel();
    private DefaultListModel modelColumnsNames = new DefaultListModel();
    
    public DataView(JFrame login,DBAccess dbAccess, String user) {
        initComponents();
        this.setTitle("Practica 9 - Usuario: "+user);
        simpleBtn.doClick();
        tableNameList.setModel(modelTableNames);
        this.dbAccess = dbAccess;
        this.login = login;
        loadTablesNames();
    }
    
    private void loadTablesNames(){
        try {
            ArrayList<String> tableNames = dbAccess.getTableNames();
            Iterator iter = tableNames.iterator();
            
            while(iter.hasNext()){
                modelTableNames.addElement(iter.next());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al acceder al servidor"
                        , "AYUDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void loadColumnsNames(String[] tableNames){
        try {
            ArrayList<String> columnsNames = dbAccess.getColumnsNames(tableNames);
            Iterator iter = columnsNames.iterator();
            
            modelColumnsNames = new DefaultListModel();
            columnNameList.setModel(modelColumnsNames);
            
            while(iter.hasNext()){
                modelColumnsNames.addElement(iter.next());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al enviar la consulta"
                        , "AYUDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        logOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNameList = new javax.swing.JList<>();
        intervalBtn = new javax.swing.JToggleButton();
        simpleBtn = new javax.swing.JToggleButton();
        multIntervalBtn = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        columnNameList = new javax.swing.JList<>();
        aboutAsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logOut.setText("Cerrar Sesión");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tablas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tableNameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableNameListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableNameList);

        buttonGroup1.add(intervalBtn);
        intervalBtn.setText("Intervalo");
        intervalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(simpleBtn);
        simpleBtn.setText("Simple");
        simpleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(multIntervalBtn);
        multIntervalBtn.setText("Intervalo Múltiple");
        multIntervalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multIntervalBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Modo de Selección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(simpleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(intervalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multIntervalBtn)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intervalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multIntervalBtn)
                .addGap(60, 60, 60))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Campos Tablas Seleccionadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane2.setViewportView(columnNameList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        aboutAsBtn.setText("Acerca de");
        aboutAsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutAsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(logOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aboutAsBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOut)
                    .addComponent(aboutAsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleBtnActionPerformed
        tableNameList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_simpleBtnActionPerformed

    private void intervalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalBtnActionPerformed
        tableNameList.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_intervalBtnActionPerformed

    private void multIntervalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multIntervalBtnActionPerformed
        tableNameList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_multIntervalBtnActionPerformed

    private void tableNameListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNameListMousePressed
        int[] selected = tableNameList.getSelectedIndices();
        String[] names = new String[selected.length];
        
        for(int i=0;i<selected.length;i++){
            names[i] = (String) modelTableNames.getElementAt(selected[i]);
        }
        
        loadColumnsNames(names);
    }//GEN-LAST:event_tableNameListMousePressed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        login.setVisible(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_logOutActionPerformed

    private void aboutAsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutAsBtnActionPerformed
       JOptionPane.showMessageDialog(rootPane,   "Aplicación para mostrar datos de una base de datos.\n" +
                                                 "Product Version: Database 1.0\n" +
                                                 "Java: 1.8.0_211; Java HotSpot(TM) 64-Bit Server VM 25.211-b12\n" +
                                                 "Runtime: Java(TM) SE Runtime Environment 1.8.0_211-b12"
                        , "AYUDA", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_aboutAsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutAsBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> columnNameList;
    private javax.swing.JToggleButton intervalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOut;
    private javax.swing.JToggleButton multIntervalBtn;
    private javax.swing.JToggleButton simpleBtn;
    private javax.swing.JList<String> tableNameList;
    // End of variables declaration//GEN-END:variables
}
